language: go

go:
- 1.8.x
- 1.9.x

services:
- redis-server

before_install:
- go get github.com/mattn/goveralls

script:
- go test -v -covermode=count -coverprofile=profile.cov . ./store/...
- $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
