name: Test
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: ['1.13', '1.14']
    name: Go ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: 5
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: 12
    - uses: jakejarvis/wait-action@v0.1.0
      with:
        time: 5s
    - run: go get -t -v ./...
    - run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
    - run: bash <(curl -s https://codecov.io/bash)
